<template>
  <h1>Hello!</h1>
  <div class="about">
    <p>Welcome to my personal page</p>
    <p>My name is Aleksandra and I am newbie frontend developer</p>
    <p class="copyrights">All icons that I used are by <a href="https://icons8.com/" target="_blank" rel="noopener nofollower norefferer">icons8🤍</a></p>
    <p>Cat is generated by <a href="https://fusionbrain.ai/" target="_blank" rel="noopener nofollower norefferer">Kandinsky</a></p>
    <div class="bg-image"></div>
  </div>
</template>

<style>
  .about {
    display: flex;
    flex-direction: column;
    align-items: start;
    justify-content: start;
    height: 50vh;
    width: max(60%, 300px);
  }
  .bg-image {
    background-image: url('../assets/catbg2.png');
    background-repeat: no-repeat;
    background-position: bottom right;
    background-size: contain;
    width: 100%;
    height: 100%;
  }
  h1 {
    text-align: center;
    color: #292929e0;
    margin-bottom: 2em;
  }
  .copyrights {
    margin-top: 2em;
  }
  p {
    outline-color: #fff;
    outline-style: solid;
    outline-width: 4px;
  }
</style>
